### ISSUE TITLE
(Normal Mode) Percentage off-centered

### ISSUE THREAD

**Issue by NonCloud9** [TechStudent10/AttemptUtils#2]
This looks very wrong because when i enter a level with the percentage on (Not matter if progress bar is on or not) the percentage moves to the left near the start of the progress bar.

![image](https://github.com/user-attachments/assets/dcd60d8d-fd89-4659-a308-25b2b41b9abc)
![image](https://github.com/user-attachments/assets/8f37bfd8-68e7-44ed-9ec8-4cd4f4460e7f)

Just toggling the "show percentage" option fixes the placement, hope it gets fixed.

**Comment by TechStudent10** [comment]
Fixed in v1.1.0, please update

**Comment by NonCloud9** [comment]
Done
