### ISSUE TITLE
Disable "Reset Attempts" button

### ISSUE THREAD

**Issue by NicolasPL64** [TechStudent10/AttemptUtils#3]
Please add a "Disable Reset Attempts button" option in the config because while using BetterInfo it's really close to the "OK" button, plus it's something some of us would never ever use.

_Thanks for the mod, btw! I was planning on doing the attempt mod eventually but you read my mind :P_

**Comment by TechStudent10** [comment]
I should've checked for conflicts with BE haha, yeah I'll add it (as well as add a fix for BE)

And no problem :D

**Comment by TechStudent10** [comment]
Fixed in v1.1.1
