### ISSUE TITLE
Reset Attempts button dissappears when switching pages whit other mods

### ISSUE THREAD

**Issue by Minekey94** [TechStudent10/AttemptUtils#7]
When you use a mod that makes the attempts tab have 2 pages, like **BetterInfo**, and switch to the second page and back, the **Reset Attempts** button dissapears.
![Screenshot_2024-07-17-18-10-08-174_com geode launcher](https://github.com/user-attachments/assets/aa45b3b3-e2cd-42f6-a476-a799f6131670)
![Screenshot_2024-07-17-18-10-12-636_com geode launcher](https://github.com/user-attachments/assets/b2e8efde-668f-46bb-8192-f571f479a9a0)
![Screenshot_2024-07-17-18-10-16-082_com geode launcher](https://github.com/user-attachments/assets/f06d73a8-a6f5-4232-af10-123fa8c02d36)

**Comment by TechStudent10** [comment]
Paginated FLAlertLayers (the popups) are not a part of standard GD to my understanding so I'm not sure how I want to handle them

**Comment by TechStudent10** [comment]
At the same time you can dismiss the popup and reopen it, which causes the button to return, so I think this isn't too bad of a bug
