### ISSUE TITLE
[Normal Mode] Percentage going way too slowly

### ISSUE THREAD

**Issue by AnhNguyenlost13** [TechStudent10/AttemptUtils#8]
Mod has been updated to version v1.2.0 and it still happens.
![image](https://github.com/user-attachments/assets/46d7170d-3f69-451f-a743-b9a24e06f3f0)

**Comment by TechStudent10** [comment]
I don't believe that this is related to Attempt Utilities because it never touches the percent (only the time label in platformer). Are you sure it's my mod?

**Comment by AnhNguyenlost13** [comment]
could no longer replicate this, closing
